### ISSUE TITLE
Modules don't have a platform

### ISSUE THREAD

**Issue by aemogie** [snowfallorg/templates#4]
Trying out snowfall for the first time today, I noticed that my `modules/snowfall/default.nix` file wasn't being loaded.

After referring to the docs, I found that the module needs to be moved into a subdirectory, based on the platform, as part of the v2 migration.

Moving `modules/snowfall` to `modules/nixos/snowfall` fixed the issue for me.

**Comment by jakehamilton** [comment]
Oh shoot you're right, thank you for catching this! I must have missed it the last time I updated the templates.

**Comment by jakehamilton** [comment]
This should now be resolved with the latest commit :)
